# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My Build'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      alphas: '["colemak_dh"]'
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
